### PR TITLE
Add TruffleRuby in CI

### PR DESCRIPTION
**Pull request by eregon**
On top of https://github.com/cookpad/grpc_kit/pull/36 to get those fixes.
Still needs a small fix in TruffleRuby to add `exception:` keyword to StringIO first, cc @andrykonchin (https://github.com/oracle/truffleruby/issues/2247#issuecomment-1222620177).

### CODE REVIEW

**Comment by eregon** [comment]
I should have marked this as a Draft PR since it's not ready yet, sorry.

**Comment by eregon** [comment]
Should be good now, the next truffleruby-dev build will have the needed fix and should pass CI.

**Comment by eregon** [comment]
@sorah Could you review and merge this?

The CI passes: https://github.com/eregon/grpc_kit/runs/7992255982?check_suite_focus=true

**Comment by sorah** [comment]
We're happy to run a CI against truffleruby but could you add separate job for truffleruby? because at this moment we don't want to (and we can't) guarantee any changes works well on truffleruby, while we fully support MRIs.

**Comment by eregon** [comment]
It's already its own "CI job" (https://github.com/eregon/grpc_kit/runs/7992255982?check_suite_focus=true), I'm not sure what you mean.
But I can use a different entry under `jobs:`, yes.

**Comment by eregon** [comment]
I pushed that.

**Comment by sorah** [comment]
> But I can use a different entry under jobs:, yes.

Yes I meant this

**Review by sorah — APPROVED** [review]

**Comment by eregon** [comment]
Thanks!

**Pull request merged**
