### PR TITLE
Bump up version to 0.3.9

### PR DESCRIPTION
**Pull request by s4ichi**
Bump up version to release: https://github.com/cookpad/grpc_kit/pull/24

@cookpad/infra Please review! and, I don't have permission to release. So, please take over the work of the release or give me permission.

### CODE REVIEW

**Comment by itkq** [comment]
@s4ichi Is this your account? https://rubygems.org/profiles/everysick

**Comment by s4ichi** [comment]
@itkq Yes, that's right. And, I just updated username: https://rubygems.org/profiles/s4ichi

**Comment by itkq** [comment]
Added to owners. Could you merge this and release it by yourself?

**Comment by s4ichi** [comment]
> Added to owners. Could you merge this and release it by yourself?

Thanks! I'll do it.

**Pull request merged**
